blog/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.auth import views
from django.contrib.auth import urls as auth_urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('sampleblog.urls')),
    url(r'^accounts/', include(auth_urls,namespace='auth')),
]

sampleblog/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings



app_name = 'sampleblog'
urlpatterns = [
    # url(r'^blog/test/$',views.test,name='test'),
    url(r'^blog/$',views.post_list,name='post_list'),

    url(r'^blog/post/like/$',views.post_like,name='post_like'),
    url(r'^blog/post/dislike/$',views.post_dislike,name='post_dislike'),
    url(r'^blog/post/(?P<post_slug>.*)/$',views.post_details,name='post_details'),
    url(r'^blog/comment/like/$',views.comment_like,name='comment_like'),
    url(r'^blog/comment/dislike/$',views.comment_dislike,name='comment_dislike'),
    url(r'^blog/category/(?P<category_slug>.*)/$',views.posts_by_category,name='posts_by_category'),
    url(r'^blog/category/$',views.category,name='category'),
    url(r'^blog/user/(?P<user>.*)/$',views.posts_by_user,name='posts_by_user'),


    url(r'^blog/register/$',views.register,name='register'),
    url(r'^blog/register/success/$',views.register_success,name='register_success'),


    url(r'^blog/dashboard/$',views.dashboard,name='dashboard'),
    url(r'^blog/dashboard/posts/$',views.dashboard_posts,name='dashboard_posts'),
    # url(r'^blog/dashboard/posts/add$',views.dashboard_posts_add,name='dashboard_posts_add'),
    url(r'^blog/dashboard/posts/(?P<post_slug>.*)/edit/$',views.dashboard_posts_edit,name='dashboard_posts_edit'),
    url(r'^blog/dashboard/posts/(?P<post_slug>.*)/delete/$',views.dashboard_posts_delete,name='dashboard_posts_delete'),


    url(r'^blog/dashboard/drafts/$',views.dashboard_drafts,name='dashboard_drafts'),
    url(r'^blog/dashboard/draft/(?P<draft_slug>.*)/$',views.dashboard_draft_details,name='dashboard_draft_details'),
    url(r'^blog/dashboard/drafts/add$',views.dashboard_drafts_add,name='dashboard_drafts_add'),
    url(r'^blog/dashboard/drafts/(?P<draft_slug>.*)/edit/$',views.dashboard_drafts_edit,name='dashboard_drafts_edit'),
    url(r'^blog/dashboard/drafts/(?P<draft_slug>.*)/delete/$',views.dashboard_drafts_delete,name='dashboard_drafts_delete'),
    url(r'^blog/dashboard/drafts/(?P<draft_slug>.*)/publish/$',views.dashboard_drafts_publish,name='dashboard_drafts_publish'),
    url(r'^blog/dashboard/drafts/category/(?P<category_slug>.*)/$',views.dashboard_drafts_by_category,name='dashboard_drafts_by_category'),
    url(r'^blog/dashboard/drafts/user/(?P<user>.*)/$',views.dashboard_drafts_by_user,name='dashboard_drafts_by_user'),




    url(r'^blog/dashboard/comments/$',views.dashboard_comments,name='dashboard_comments'),
    url(r'^blog/dashboard/comments/(?P<comment_slug>.*)/edit/$',views.dashboard_comments_edit,name='dashboard_comments_edit'),
    url(r'^blog/dashboard/comments/(?P<comment_slug>.*)/delete/$',views.dashboard_comments_delete,name='dashboard_comments_delete'),


    url(r'^blog/dashboard/profile/$',views.dashboard_profile,name='dashboard_profile'),
    url(r'^blog/dashboard/profile/add/$',views.dashboard_profile_add,name='dashboard_profile_add'),
    url(r'^blog/dashboard/profile/edit/$',views.dashboard_profile_edit,name='dashboard_profile_edit'),
    url(r'^blog/dashboard/profile/delete/$',views.dashboard_profile_delete,name='dashboard_profile_delete'),






]

sampleblog/forms.py
from django import forms
from .models import Post, Comment, Profile,Category
from django.contrib.auth.models import User
from django.contrib.auth import password_validation

class Draft_form(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title','text',)


class Category_form(forms.ModelForm):
    class Meta:
        model = Category
        fields = ('category',)


class Register_form(forms.ModelForm):
    # help_text=password_validation.password_validators_help_text_html()
    password = forms.CharField(widget=forms.PasswordInput,)
    class Meta:
        model = User
        fields = ('username','email','password')

    def clean_password(self):
        data = self.cleaned_data['password']
        if password_validation.validate_password(data) is None:
            return data


class Comment_form(forms.ModelForm):
    text = forms.CharField(widget=forms.Textarea, label='')
    class Meta:
        model = Comment
        fields = ('text',)


class Profile_form(forms.ModelForm):

    class Meta:
        model = Profile
        fields = ('first_name','last_name','text','avatar')

sampleblog/views.py
from django.shortcuts import render,redirect,get_object_or_404
from sampleblog.models import Post, Comment, Profile, Category
from django.contrib.auth.models import User
from .forms import Draft_form, Register_form, Comment_form, Profile_form, Category_form
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse,HttpResponseRedirect,Http404
from django.core.urlresolvers import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.utils.text import slugify
from django.contrib import messages
from django.utils import timezone

# Create your views here.

def post_list(request):
    post_list = Post.objects.filter(published_date__isnull = False).order_by('-published_date')
    post_list_count = post_list.count()
    post_list_state = "posts"

    if post_list_count == 0:
        messages.info(request, 'There are no published posts yet.', extra_tags="alert alert-info")
        post_list_state = "post"
    if post_list_count == 1:
        post_list_state = "post"

    paginator = Paginator(post_list, 5) # Show 25 contacts per page
    page = request.GET.get('page')
    try:
        post_list_current_page = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        post_list_current_page = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        post_list_current_page = paginator.page(paginator.num_pages)

    context = {
    'post_list_current_page':post_list_current_page,
    'post_list_count':post_list_count,
    'post_list_state':post_list_state
    }
    return render(request,'sampleblog/post_list.html',context)



def post_details(request, post_slug):

    current_post = Post.objects.get(slug = post_slug)
    current_comments = Comment.objects.filter(post = current_post,parent__isnull=True).order_by('-created_date')
    current_comments_total = Comment.objects.filter(post = current_post).order_by('-created_date')
    current_comments_count = current_comments_total.count()
    current_comments_state = "comments"
    # current_replies = Comment.objects.filter(post = current_post,parent__isnull=False ).order_by('-created_date')
    # current_comments = Comment.objects.filter(post = current_post,parent__isnull=True).order_by('-created_date')
    # print(current_comments_no_parent.count())

    paginator = Paginator(current_comments, 5) # Show 25 contacts per page
    page = request.GET.get('page')
    try:
        current_comments_current_page = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        current_comments_current_page = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        current_comments_current_page = paginator.page(paginator.num_pages)

    if request.method =='POST':
        comment_form = Comment_form(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.user = request.user
            comment.post = current_post
            parent_id = request.POST.get('parent_id')
            print(parent_id)
            if parent_id:
                comment.parent = Comment.objects.get(id=parent_id)
            comment.save()
            messages.info(request, 'Comment added.', extra_tags="alert alert-info")
            # return HttpResponseRedirect(reverse('post_list', ))
            return redirect('sampleblog:post_details',post_slug=current_post.slug)

    else:
        comment_form = Comment_form(auto_id=False)
        if current_comments_count == 0:
            messages.info(request, 'There are no comments yet.', extra_tags="alert alert-info")
            current_comments_state = "comment"
        if current_comments_count == 1:
            current_comments_state = "comment"

        context = {
        'current_post': current_post,
        'current_comments_current_page':current_comments_current_page,
        'current_comments_count':current_comments_count,
        'current_comments_total':current_comments_total,
        'current_comments_state':current_comments_state,
        'comment_form':comment_form
        }

        return render(request,'sampleblog/post_details.html',context)


def comment_like(request):

         comment_id = request.GET.get('comment_id')
         current_comment = Comment.objects.get(slug=comment_id)

         likes_count = current_comment.likes + 1
         current_comment.likes = likes_count
         current_comment.save()
         return HttpResponse(likes_count)

def comment_dislike(request):

         comment_id = request.GET.get('comment_id')
         current_comment = Comment.objects.get(slug=comment_id)

         dislikes_count = current_comment.dislikes + 1
         current_comment.dislikes = dislikes_count
         current_comment.save()
         return HttpResponse(dislikes_count)

def post_like(request):

         post_id = request.GET.get('post_id')
         current_post = Post.objects.get(slug=post_id)

         likes_count = current_post.likes + 1
         current_post.likes = likes_count
         current_post.save()
         return HttpResponse(likes_count)

def post_dislike(request):

         post_id = request.GET.get('post_id')
         current_post = Post.objects.get(slug=post_id)

         dislikes_count = current_post.dislikes + 1
         current_post.dislikes = dislikes_count
         current_post.save()
         return HttpResponse(dislikes_count)

def posts_by_category(request, category_slug):
    posts_by_category = Post.objects.filter(category__slug = category_slug,published_date__isnull = False).order_by('-published_date')
    posts_by_category_count = posts_by_category.count()
    posts_by_category_state = "posts"
    current_category = category_slug.title().replace("-"," ")


    if posts_by_category_count == 0:
        messages.info(request, 'This category does not have any posts yet.', extra_tags="alert alert-info")
        posts_by_category_state = "post"

    if posts_by_category_count == 1:
        posts_by_category_state = "post"

    paginator = Paginator(posts_by_category, 5) # Show 25 contacts per page
    page = request.GET.get('page')
    try:
        posts_by_category_current_page = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        posts_by_category_current_page = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        posts_by_category_current_page = paginator.page(paginator.num_pages)

    context = {
    'posts_by_category_current_page':posts_by_category_current_page,
    'posts_by_category_count':posts_by_category_count,
    'current_category':current_category,
    'posts_by_category_state':posts_by_category_state
    }

    return render(request,'sampleblog/posts_by_category.html',context)



def category(request):

    category_field = Category._meta.get_field('category')
    category_field_choices = category_field.choices

    category_field_choices_list=[]
    category_field_choices_slug_list = []
    category_field_choices_count_list = []

    for x in category_field_choices:
        y = x[0]
        category_field_choices_list.append(y)

    for x in category_field_choices:
        y = slugify(x[0])
        category_field_choices_slug_list.append(y)

    for x in category_field_choices_list:
        posts_by_category = Post.objects.filter(category__category = x,published_date__isnull = False)
        posts_by_category_count = posts_by_category.count()
        category_field_choices_count_list.append(posts_by_category_count)


    category_field_choices_final_list =list(zip(category_field_choices_list, category_field_choices_slug_list,category_field_choices_count_list))

    print(category_field_choices_final_list)
    context = {
    'category_field_choices_final_list':category_field_choices_final_list,
    }

    return render(request,'sampleblog/category.html',context)

def posts_by_user(request, user):
    posts_by_user = Post.objects.filter(user__username = user,published_date__isnull = False).order_by('-published_date')
    current_user = user
    posts_by_user_state = 'posts'
    posts_by_user_count = posts_by_user.count()


    if posts_by_user_count == 0:
        posts_by_user_state = 'post'

    if posts_by_user_count == 1:
        posts_by_user_state = 'post'


    paginator = Paginator(posts_by_user, 5) # Show 25 contacts per page
    page = request.GET.get('page')
    try:
        posts_by_user_current_page = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        posts_by_user_current_page = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        posts_by_user_current_page = paginator.page(paginator.num_pages)

    context = {
    'posts_by_user_current_page':posts_by_user_current_page,
    'current_user':current_user,
    'posts_by_user_count':posts_by_user_count,
    'posts_by_user_state':posts_by_user_state
    }
    return render(request,'sampleblog/posts_by_user.html',context)


def register(request):
    if request.method =='POST':
        register_form = Register_form(request.POST)
        if register_form.is_valid():
            user = register_form.save(commit=False)
            password = register_form.cleaned_data['password']
            user.set_password(password)
            user.save()
            # p = Profile.objects.create(user=user)
            return redirect('sampleblog:register_success')
        # else:
        #     print (register_form.errors)
    else:
        register_form = Register_form()

    context ={
    'register_form':register_form
    }

sampleblog/templates/sampleblog/dashboard.html
{% extends "sampleblog/post_list.html" %}
{% load static %}

{% block title %}{% endblock title %}

{% block content %}

<main>
  <section >
    <div class='container'>

      <div>
        <ul class="nav nav-tabs ">
          <li role="presentation" class="active"><a href="{% url 'sampleblog:dashboard' %}">dashboard</a></li>
          <li role="presentation"><a href='{% url 'sampleblog:dashboard_drafts' %}'>drafts</a></li>
          <li role="presentation"><a href='{% url 'sampleblog:dashboard_posts' %}'>published posts</a></li>
          <li role="presentation"><a href='{% url 'sampleblog:dashboard_comments' %}'>my comments</a></li>
          <li role="presentation"><a href='{% url 'sampleblog:dashboard_profile' %}'>my profile</a></li>
          <li role="presentation"><a href='{% url 'sampleblog:dashboard_profile' %}'>account settings</a></li>
          <li role="presentation"><a href='{% url 'auth:logout' %}'>log out</a></li>
        </ul>
      </div>

      <div >
        <div>
          <h1>Hello, {{current_user.username}}</h1>
        </div>

        {% if messages %}
        <div>
          {% for message in messages %}
          <div class="{{ message.tags }} alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <p>{{ message }}</p>
          </div>
          {% endfor %}
        </div>
        {% endif %}

        <div>
          {% if current_drafts_count != 0 %}
          <div>
            <h2>my drafts</h2>
            {% for draft in current_drafts %}
            <div>
              <div>
                <h2><a href="{% url 'sampleblog:dashboard_draft_details' draft_slug=draft.slug %}">{{draft.title}}</a></h2>
                <h4><span class="label label-default">Draft</span></h4>
              </div>

              <div>
                <span><a href='{% url 'sampleblog:dashboard_drafts_by_category' category_slug=draft.category.slug %}'>{{draft.category.category}}</a></span>
              </div>

              <div>
                <span>{{draft.created_date}} by <a href='{% url 'sampleblog:dashboard_drafts_by_user' user=draft.user.username %}'>{{draft.user.username}}</a></span>
              </div>

              <div><p>{{draft.text}}</p></div>
            </div>
            {% endfor %}
            <a class='btn btn-primary' href='{% url 'sampleblog:dashboard_drafts' %}'>see all drafts</a>
          </div>
          {% endif %}


          {% if current_posts_count != 0 %}
          <div>
            <h2>Published posts</h2>
            {% for post in current_posts %}
            <div>
              <div>
                <h2><a href="{% url 'sampleblog:post_details' post_slug=post.slug %}">{{post.title}}</a></h2>
              </div>

              <div>
                <span><a href='{% url 'sampleblog:posts_by_category' category_slug=post.category.slug %}'>{{post.category.category}}</a></span>
              </div>

              <div>
                <span>{{post.published_date}} by <a href='{% url 'sampleblog:posts_by_user' user=post.user.username %}'>{{post.user.username}}</a></span>
              </div>

              <div><p>{{post.text}}</p></div>

              <div>
                <a class='btn btn-primary' href='{% url 'sampleblog:dashboard_posts_edit' post_slug=post.slug %}'>edit</a>
                <a class='btn btn-primary' href='{% url 'sampleblog:dashboard_posts_delete' post_slug=post.slug %}'>delete</a>
              </div>
            </div>
            {% endfor %}
          </div>
          {% endif %}



          {% if current_comments_count != 0 %}
          <div>
            <h2>my comments</h2>
            {% for comment in current_comments %}
            <div>
              <div class="media">
                <div class="media-left">
                  <a href="#">
                    <img class="media-object" src="{{ current_user.profile.avatar.url }}" alt="Smiley face" width="60px" height="60px" >
                  </a>
                </div>
                <div class="media-body">
                  <div><p>{{comment.text}}</p></div>
                  <div>
                    <span>{{comment.created_date}} by <a href='{% url 'sampleblog:posts_by_user' user=comment.user.username %}'>{{comment.user.username}}</a></span>
                  </div>
                </div>
              </div>
            </div>
            {% endfor %}

            <a class='btn btn-primary' href='{% url 'sampleblog:dashboard_comments' %}'>see all comments</a>
          </div>
          {% endif %}
        </div>

      </div>


    </div>
  </section>
</main>
{% endblock content%}

sampleblog/templates/sampleblog/dashboard_comments.html
{% extends "sampleblog/post_list.html" %}
{% load static %}

{% block title %}{% endblock title %}

{% block content %}

<main>
  <section >
    <div class='container'>

      <div >
        <ul class="nav nav-tabs">
          <li role="presentation"><a href="{% url 'sampleblog:dashboard' %}">dashboard</a></li>
          <li role="presentation"><a href='{% url 'sampleblog:dashboard_drafts' %}'>drafts</a></li>
          <li role="presentation"><a href='{% url 'sampleblog:dashboard_posts' %}'>published posts</a></li>
          <li role="presentation" class="active"><a href='{% url 'sampleblog:dashboard_comments' %}'>my comments</a></li>
          <li role="presentation"><a href='{% url 'sampleblog:dashboard_profile' %}'>my profile</a></li>
          <li role="presentation"><a href='{% url 'sampleblog:dashboard_profile' %}'>account settings</a></li>
          <li role="presentation"><a href='{% url 'auth:logout' %}'>log out</a></li>
        </ul>
      </div>

      <div >
        <div>
          <h1>Hello, {{current_user.username}}</h1>
        </div>

        {% if messages %}
        <div>
          {% for message in messages %}
          <div class="{{ message.tags }} alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <p>{{ message }}</p>
          </div>
          {% endfor %}
        </div>
        {% endif %}

        <div>
          <a class='btn btn-primary' href='{% url 'sampleblog:post_list' %}'>Read the blogs</a>
        </div>


        {% if current_comments_count != 0 %}
        <div>
          <h2>my comments</h2>
          {% for comment in current_comments_current_page %}
          <div>
            <div class="media">
              <div class="media-left">
                <a href="#">
                  <img class="media-object" src="{{ current_user.profile.avatar.url }}" alt="Smiley face" width="60px" height="60px" >
                </a>
              </div>
              <div class="media-body">

                <div><p>{{comment.text}}</p></div>
                <div>
                  <span>{{comment.created_date}} by <a href='{% url 'sampleblog:posts_by_user' user=comment.user.username %}'>{{comment.user.username}}</a></span>
                </div>
              </div>
            </div>
            <div>
              <a class='btn btn-primary' href='{% url 'sampleblog:dashboard_comments_edit' comment_slug=comment.slug %}'>edit</a>
              <a class='btn btn-primary' href='{% url 'sampleblog:dashboard_comments_delete' comment_slug=comment.slug %}'>delete</a>
            </div>
          </div>
          {% endfor %}

          <ul class="pagination">
            {% if current_comments_current_page.has_previous %}
            <li><a href="?page={{ current_comments_current_page.previous_page_number }}">&laquo;</a></li>
            {% else %}
            <li class="disabled"><span>&laquo;</span></li>
            {% endif %}
            {% for i in current_comments_current_page.paginator.page_range %}
            {% if current_comments_current_page.number == i %}
            <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
            {% else %}
            <li><a href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
            {% endfor %}
            {% if current_comments_current_page.has_next %}
            <li><a href="?page={{ current_comments_current_page.next_page_number }}">&raquo;</a></li>
            {% else %}
            <li class="disabled"><span>&raquo;</span></li>
            {% endif %}
          </ul>

        </div>
        {% endif %}

      </div>
    </div>
  </section>
</main>
{% endblock content%}

sampleblog/templates/sampleblog/dashboard_comments_edit.html
{% extends "sampleblog/post_list.html" %}
{% load static %}
{% load widget_tweaks %}
{% block title %}{% endblock title %}

{% block content %}

<main>

  <section >
    <div class='container'>
      <div class='row'>
        <div class='col-lg-4'>
      <h3>edit comment</h3>
      <form action="" method='post'>
        {% csrf_token %}
        <div class="form-group ">
          {{ comment_form.text.errors }}
          {{ comment_form.text.label_tag }}
          {{ comment_form.text|add_class:"form-control"   }}
        </div>

        <div><input class="btn btn-primary" id='submit'type='submit' value='edit comment'></div>

      </form>
  </div>
</div>
  </div>
  </section>
</main>


{% endblock content%}

sampleblog/templates/sampleblog/dashboard_draft_details.html
{% extends "sampleblog/post_list.html" %}
{% load static %}
{% load widget_tweaks %}
{% block title %}{% endblock title %}

{% block content %}

<main>
  <section >
    <div class='container' >

      <div >
        <div>
          <h2><a href="{% url 'sampleblog:dashboard_draft_details' draft_slug=current_draft.slug %}">{{current_draft.title}}</a></h2>
          <h4><span class="label label-default">Draft</span></h4>
        </div>

        <div>
          <span><a href='{% url 'sampleblog:dashboard_drafts_by_category' category_slug=current_draft.category.slug %}'>{{current_draft.category.category}}</a></span>
        </div>

        <div>
          <span>{{current_draft.created_date}} by <a href='{% url 'sampleblog:dashboard_drafts_by_user' user=current_draft.user.username %}'>{{current_draft.user.username}}</a></span>
        </div>

        <div><p>{{current_draft.text}}</p></div>
      </div>







    </div>
  </section>
</main>
{% endblock content %}

sampleblog/templates/sampleblog/dashboard_drafts.html
{% extends "sampleblog/post_list.html" %}
{% load static %}

{% block title %}{% endblock title %}

{% block content %}

<main>
  <section >
    <div class='container'>

      <div >
        <ul class="nav nav-tabs">
          <li role="presentation"><a href="{% url 'sampleblog:dashboard' %}">dashboard</a></li>
          <li role="presentation" class="active"><a href='{% url 'sampleblog:dashboard_drafts' %}'>drafts</a></li>
          <li role="presentation"><a href='{% url 'sampleblog:dashboard_posts' %}'>published posts</a></li>
          <li role="presentation"><a href='{% url 'sampleblog:dashboard_comments' %}'>my comments</a></li>
          <li role="presentation"><a href='{% url 'sampleblog:dashboard_profile' %}'>my profile</a></li>
          <li role="presentation"><a href='{% url 'sampleblog:dashboard_profile' %}'>account settings</a></li>
          <li role="presentation"><a href='{% url 'auth:logout' %}'>log out</a></li>
        </ul>
      </div>


      <div >
        <div>
          <h1>Hello, {{current_user.username}}</h1>
        </div>

        {% if messages %}
        <div>
          {% for message in messages %}
          <div class="{{ message.tags }} alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <p>{{ message }}</p>
          </div>
          {% endfor %}
        </div>
        {% endif %}

        <div>
          <a class='btn btn-primary' href='{% url 'sampleblog:dashboard_drafts_add' %}'>add post</a>
        </div>

        {% if current_drafts_count != 0 %}
        <div>
          <h2>My Drafts</h2>
          {% for draft in current_drafts_current_page %}
          <div>
            <div>
              <h2><a href="{% url 'sampleblog:dashboard_draft_details' draft_slug=draft.slug %}">{{draft.title}}</a></h2>
              <h4><span class="label label-default">Draft</span></h4>
            </div>

            <div>
              <span><a href='{% url 'sampleblog:dashboard_drafts_by_category' category_slug=draft.category.slug %}'>{{draft.category.category}}</a></span>
            </div>

            <div>
              <span>{{draft.created_date}} by <a href='{% url 'sampleblog:dashboard_drafts_by_user' user=draft.user.username %}'>{{draft.user.username}}</a></span>
            </div>

            <div><p>{{draft.text}}</p></div>

            <div>
              <a class='btn btn-primary' href='{% url 'sampleblog:dashboard_drafts_edit' draft_slug=draft.slug %}'>edit</a>
              <a class='btn btn-primary' href='{% url 'sampleblog:dashboard_drafts_delete' draft_slug=draft.slug %}'>delete</a>
              <a class='btn btn-primary' href='{% url 'sampleblog:dashboard_drafts_publish' draft_slug=draft.slug %}'>publish</a>
            </div>
          </div>
          {% endfor %}

          <ul class="pagination">
            {% if current_drafts_current_page.has_previous %}
            <li><a href="?page={{ current_drafts_current_page.previous_page_number }}">&laquo;</a></li>
            {% else %}
            <li class="disabled"><span>&laquo;</span></li>
            {% endif %}
            {% for i in current_drafts_current_page.paginator.page_range %}
            {% if current_drafts_current_page.number == i %}
            <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
            {% else %}
            <li><a href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
            {% endfor %}
            {% if current_drafts_current_page.has_next %}
            <li><a href="?page={{ current_drafts_current_page.next_page_number }}">&raquo;</a></li>
            {% else %}
            <li class="disabled"><span>&raquo;</span></li>
            {% endif %}
          </ul>

        </div>
        {% endif %}

      </div>
    </div>
  </section>
</main>




{% endblock content %}

sampleblog/templates/sampleblog/dashboard_drafts_edit.html
{% extends "sampleblog/post_list.html" %}
{% load static %}
{% load widget_tweaks %}
{% block title %}{% endblock title %}

{% block content %}

<main>

  <section >
    <div class='container'>
      <div class='row'>
        <div class='col-lg-4'>
      <h3>edit draft</h3>
      <form action="" method='post'>
        {% csrf_token %}
        <!-- {{form.as_p}} -->
        <div class="form-group ">
          {{ draft_form.title.label_tag }}
          {{ draft_form.title|add_class:"form-control"   }}
          {{ draft_form.title.errors }}
        </div>
        <div class="form-group">
          {{ draft_form.text.label_tag }}
          {{ draft_form.text|add_class:"form-control"   }}
          {{ draft_form.text.errors }}
        </div>
        <div class="form-group">
          {{ category_form.category.label_tag }}
          {{ category_form.category|add_class:"form-control"   }}
          {{ category_form.category.errors }}
        </div>
        <div><input class="btn btn-primary" id='submit'type='submit' value='edit draft'></div>


    </form>
  </div>
</div>
</div>
  </section>
</main>


{% endblock content%}